#!/bin/sh

for i in ML-KEM-{512,768,1024}.{pub,crt}
do
    der2ascii -pem -i $i -o $i.tmp
    fold -w 64 $i.tmp > $i.txt
    rm $i.tmp
done

# Process priv key files with -both, -expanded, and -seed suffixes
for i in ML-KEM-{512,768,1024}-{both,expanded,seed}.priv
do
    der2ascii -pem -i $i -o $i.tmp
    fold -w 64 $i.tmp > $i.txt
    rm $i.tmp
done
